# Generated by Django 6.0.2 on 2026-02-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="notifications",
            field=models.BooleanField(default=False),
        ),
    ]
