# Generated by Django 6.0.2 on 2026-02-17 18:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0002_appsettings_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AppSettings",
            new_name="AppSettingsModel",
        ),
    ]
