# Generated by Django 6.0.2 on 2026-02-16 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="is_parent_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="parent_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
