# Generated by Django 6.0.2 on 2026-02-18 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customusermodel_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customusermodel",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
