# Generated by Django 6.0.2 on 2026-04-26 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userblockmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='is_parent_approved',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='parent_email',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Children_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(blank=True, max_length=100, null=True)),
                ('child_image', models.ImageField(blank=True, null=True, upload_to='children_images/')),
                ('child_age', models.IntegerField(blank=True, null=True)),
                ('child_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('favourite_themes', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Children Profile',
                'verbose_name_plural': 'Children Profile',
                'db_table': 'Children Profile Table',
            },
        ),
        migrations.DeleteModel(
            name='UserBlockModel',
        ),
    ]
