# Generated by Django 6.0.2 on 2026-05-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_customusermodel_age_group_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Children_Profile",
            new_name="ChildrenProfileModel",
        ),
    ]
