# Generated by Django 6.0.2 on 2026-05-07 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_customusermodel_age_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildrenProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "child_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="children_images/"
                    ),
                ),
                ("child_age", models.IntegerField(blank=True, null=True)),
                (
                    "child_gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "favourite_themes",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Children Profile",
                "verbose_name_plural": "Children Profile",
                "db_table": "Children Profile Table",
            },
        ),
        migrations.DeleteModel(
            name="Children_Profile",
        ),
    ]
