# Generated by Django 6.0.2 on 2026-05-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_childrenprofilemodel_delete_children_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Designates whether this user has a paid subscription.'),
        ),
    ]
