# Generated by Django 6.0.2 on 2026-05-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customusermodel_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_pictures/'),
        ),
    ]
