# Generated by Django 6.0.2 on 2026-06-05 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0003_pricingplanmodel"),
        ("users", "0012_customusermodel_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="pricing_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscribers",
                to="admins.pricingplanmodel",
            ),
        ),
    ]
