# Generated by Django 6.0.2 on 2026-02-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customusermodel_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customusermodel",
            options={"verbose_name": "User", "verbose_name_plural": "Users Account"},
        ),
    ]
