# Generated by Django 6.0.2 on 2026-06-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0002_reportmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPlanModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price_per_month",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("details", models.TextField()),
                ("points_included", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Pricing Plan",
                "verbose_name_plural": "Pricing Plans",
                "db_table": "Pricing Plans Table",
            },
        ),
    ]
