# Generated by Django 6.0.2 on 2026-06-05 21:04

from django.db import migrations


def populate_pricing_plans(apps, schema_editor):
    PricingPlanModel = apps.get_model('admins', 'PricingPlanModel')
    
    # Check if plans already exist to avoid duplication
    if not PricingPlanModel.objects.exists():
        plans = [
            {
                "name": "Basic",
                "price_per_month": 0.00,
                "details": "Free plan with limited points.",
                "points_included": 10
            },
            {
                "name": "Standard",
                "price_per_month": 4.99,
                "details": "Standard plan with moderate points.",
                "points_included": 50
            },
            {
                "name": "Premium",
                "price_per_month": 9.99,
                "details": "Premium plan with max points.",
                "points_included": 150
            }
        ]
        for plan in plans:
            PricingPlanModel.objects.create(**plan)

class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0003_pricingplanmodel"),
    ]

    operations = [
        migrations.RunPython(populate_pricing_plans),
    ]
