# Generated by Django 6.0.2 on 2026-05-07 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0010_childrenprofilemodel_delete_children_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("theme", models.CharField(max_length=100)),
                ("full_story", models.TextField(blank=True, null=True)),
                ("language", models.CharField(default="en", max_length=100)),
                ("selected_voices", models.CharField(max_length=100)),
                (
                    "story_id_ai",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="stories/audio/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "children_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.childrenprofilemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoiceCloneModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voice_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("voice_id_ai", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloned_voices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
