# Generated by Django 6.0.2 on 2026-05-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storymodel",
            name="cloned_voice_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="storymodel",
            name="custom_theme",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="storymodel",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "French"),
                    ("es", "Spanish"),
                    ("ar", "Arabic"),
                    ("hi", "Hindi"),
                    ("de", "German"),
                    ("pt", "Portuguese"),
                ],
                default="en",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="storymodel",
            name="selected_voices",
            field=models.CharField(
                choices=[
                    ("primary_female", "Primary Female"),
                    ("primary_male", "Primary Male"),
                    ("secondary_female", "Secondary Female"),
                    ("secondary_male", "Secondary Male"),
                    ("child_female", "Child Female"),
                    ("child_male", "Child Male"),
                ],
                default="primary_female",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="storymodel",
            name="theme",
            field=models.CharField(
                choices=[
                    ("adventure", "Adventure"),
                    ("fantasy", "Fantasy"),
                    ("animals", "Animals"),
                    ("science", "Science"),
                    ("friendship", "Friendship"),
                    ("bedtime", "Bedtime"),
                    ("custom", "Custom"),
                ],
                default="bedtime",
                max_length=50,
            ),
        ),
    ]
