# Generated by Django 6.0.2 on 2026-05-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_storymodel_cloned_voice_id_storymodel_custom_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymodel',
            name='word_timestamps',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
