# Generated by Django 6.0.2 on 2026-06-05 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0003_storymodel_word_timestamps"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryChapterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_number", models.IntegerField(default=1)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="stories/chapters/audio/"
                    ),
                ),
                ("word_timestamps", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="story.storymodel",
                    ),
                ),
            ],
            options={
                "ordering": ["chapter_number"],
            },
        ),
    ]
