# Generated by Django 6.0.2 on 2026-05-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Used in SEO-friendly URL paths. Automatically generated if left blank.', max_length=255, unique=True)),
                ('author', models.CharField(default='WonderTales Hub', max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/images/')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated list of tags.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title tag fallback (optional).', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO Meta Description.', null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO Meta Keywords.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-created_at'],
            },
        ),
    ]
